services:
  app:
    image: socketio-app:latest
    networks:
      - my_net
    ports:
      # - 3000:3000
      - published: 3000
        target: 3000
        protocol: tcp
        mode: ingress
    depends_on:
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis:latest
    networks:
      - my_net
    ports:
      - 6379:6379

networks:
  my_net:
    driver: overlay
